services:
  - type: web
    name: book-management-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - fromEnvVar: DB_URL
      - fromEnvVar: DB_USER
      - fromEnvVar: DB_PASSWORD
      - fromEnvVar: CLOUDINARY_CLOUD_NAME
      - fromEnvVar: CLOUDINARY_API_KEY
      - fromEnvVar: CLOUDINARY_API_SECRET
      - fromEnvVar: MAIL_USERNAME
      - fromEnvVar: MAIL_APP_PASSWORD
